"""Where to put the face on a customiser shape.

The eyes live on a sphere, and radius_at_angle re-attaches them to the real
outline pro-rata to the local radius. That places their CENTRE correctly, but
the eye has a size: a silhouette narrow in its direction pushes it against the
edge until the mask opens it outwards.

This module solves the problem ONCE, at build time, and yields a table of
offsets. The table is a module constant built from pure data (like the blink
schedule in face.py): deterministic and stateless, so engine.sample(t) stays a
pure function of time. This is pose space deformation (Lewis, Cordner & Fong,
SIGGRAPH 2000): a corrective authored per pose, resolved at setup and merely
looked up at runtime.

The runtime reads the committed table (see _eyefit_table.py), regenerated by
tools/build_eyefit.py. The solver itself is kept here for that regeneration.
"""

import math

from . import _eyefit_table
from .expressions import EXPRESSIONS
from .face import eye_poses
from .shape import Silhouette, radius_at_angle, to_points
from .skins import SHAPES
from .states import STATES

# Reference radius of the solver. The returned offset is in units of this radius.
R = 100

# Map a radii list (by reference, like the engine's guards) to its shape id.
_REF_TO_ID = {id(s["radii"]): s["id"] for s in SHAPES}
_TABLE = _eyefit_table.TABLE

_NUL = {"x": 0.0, "y": 0.0}


def decalage_des_yeux(radii, state, expr):
    """Offset to apply to both eyes for this shape/state/expression, in
    ball-radius units (the engine rescales it). Zero whenever the shape is not
    in the catalogue, which covers None and the circle."""
    if radii is None:
        return _NUL
    shape_id = _REF_TO_ID.get(id(radii))
    if shape_id is None:
        return _NUL
    row = _TABLE.get(shape_id, {})
    return row.get(state + "|" + (expr or "")) or row.get(state + "|") or _NUL


# ---------------------------------------------------------------------------
# Solver (used only by tools/build_eyefit.py to regenerate _eyefit_table.py).
# ---------------------------------------------------------------------------

DERIVE_YAW = 5.5 + 1.6
DERIVE_PITCH = 4.2 + 1.3
DERIVE_X = 0.006
DERIVE_Y = 0.007
FLOTTEMENT = math.hypot(DERIVE_X, DERIVE_Y) * R
DIRECTIONS = 12
DICHOTOMIE = 8


def _empreintes(visage, sil, radii):
    out = []
    poses = eye_poses(visage["gaze"], R, visage["split"])
    for i in range(2):
        e = poses[i]
        if e["depth"] <= 0.02:
            continue
        cfg = visage["eyes"][i]
        phi = (cfg.get("tilt", 0.0) * math.pi) / 180.0
        cp = math.cos(phi)
        sp = math.sin(phi)
        ax = e["a"] * cp + e["c"] * sp
        ay = e["b"] * cp + e["d"] * sp
        cx = -e["a"] * sp + e["c"] * cp
        cy = -e["b"] * sp + e["d"] * cp
        hw = max(cfg["w"] * R, 0.01) / 2.0
        hh = max(cfg["h"] * R, 0.01) / 2.0
        r = min(hw, hh)
        long_ = hh > hw
        demi = (hh - r) if long_ else (hw - r)
        fit = radius_at_angle(radii, math.atan2(e["y"], e["x"]) - sil.rot)
        out.append({
            "x": e["x"] * fit,
            "y": e["y"] * fit,
            "ax": (cx if long_ else ax) * demi,
            "ay": (cy if long_ else ay) * demi,
            "r": r,
            "m": [ax, ay, cx, cy],
        })
    return out


def _approche(pts, x0, y0, x1, y1):
    sx = x1 - x0
    sy = y1 - y0
    len2 = sx * sx + sy * sy
    best = float("inf")
    vx = 0.0
    vy = 0.0
    for p in pts:
        t = ((p.x - x0) * sx + (p.y - y0) * sy) / len2 if len2 > 0 else 0.0
        if t < 0:
            t = 0.0
        elif t > 1:
            t = 1.0
        ex = x0 + t * sx - p.x
        ey = y0 + t * sy - p.y
        d2 = ex * ex + ey * ey
        if d2 < best:
            best = d2
            vx = ex
            vy = ey
    d = math.sqrt(best)
    if d > 1e-9:
        return {"d": d, "ux": vx / d, "uy": vy / d}
    return {"d": d, "ux": 0.0, "uy": 0.0}


def _pire(pts, emps, tx, ty):
    marge = float("inf")
    ux = 0.0
    uy = 0.0
    for e in emps:
        x = e["x"] + tx
        y = e["y"] + ty
        a = _approche(pts, x - e["ax"], y - e["ay"], x + e["ax"], y + e["ay"])
        m0, m1, m2, m3 = e["m"]
        rayon = e["r"] * math.hypot(m0 * a["ux"] + m1 * a["uy"], m2 * a["ux"] + m3 * a["uy"]) + FLOTTEMENT
        if a["d"] - rayon < marge:
            marge = a["d"] - rayon
            ux = a["ux"]
            uy = a["uy"]
    return {"marge": marge, "ux": ux, "uy": uy}


def _resous(epreuves):
    if not epreuves:
        return (0.0, 0.0)

    def marge(tx, ty):
        m = float("inf")
        for ep in epreuves:
            m = min(m, _pire(ep["contour"], ep["empreintes"], tx, ty)["marge"])
        return m

    requis = float("inf")
    for ep in epreuves:
        requis = min(requis, _pire(ep["calContour"], ep["reference"], 0.0, 0.0)["marge"])

    mx = 0.0
    my = 0.0
    emps = epreuves[0]["empreintes"]
    for e in emps:
        mx -= e["x"] / len(emps)
        my -= e["y"] / len(emps)
    course = max(0.35 * R, math.hypot(mx, my) * 1.25)
    requis = min(requis, marge(mx, my))

    depart = marge(0.0, 0.0)
    if depart >= requis and depart >= 0:
        return (0.0, 0.0)
    cible = max(requis, 0.0)

    meilleur_x = 0.0
    meilleur_y = 0.0
    meilleure_norme = float("inf")
    secours_x = 0.0
    secours_y = 0.0
    secours = depart

    for d in range(DIRECTIONS):
        a = (d / DIRECTIONS) * math.pi * 2
        ux = math.cos(a)
        uy = math.sin(a)
        if marge(ux * course, uy * course) < cible:
            for k in (0.3, 0.6, 1.0):
                m = marge(ux * course * k, uy * course * k)
                if m > secours:
                    secours = m
                    secours_x = ux * course * k
                    secours_y = uy * course * k
            continue
        bas = 0.0
        haut = course
        for _ in range(DICHOTOMIE):
            mid = (bas + haut) / 2.0
            if marge(ux * mid, uy * mid) >= cible:
                haut = mid
            else:
                bas = mid
        if haut < meilleure_norme:
            meilleure_norme = haut
            meilleur_x = ux * haut
            meilleur_y = uy * haut

    x = secours_x if meilleure_norme == float("inf") else meilleur_x
    y = secours_y if meilleure_norme == float("inf") else meilleur_y
    return (round(x / R, 6), round(y / R, 6))


def _visage_de(def_, pose, expr):
    if def_["baseFace"] and expr is not None:
        return {"gaze": expr["gaze"], "split": expr["split"], "eyes": expr["eyes"]}
    return {"gaze": pose["gaze"], "split": pose["split"], "eyes": pose["eyes"]}


def _dates(def_):
    def signature(p):
        return repr([p["gaze"], p["split"], p["eyes"], p["sil"].rot, p["sil"].cx, p["sil"].cy, p["sil"].sx, p["sil"].sy])

    if signature(def_["pose"](0)) == signature(def_["pose"](def_["duration"])):
        return [0.0]
    n = 3
    return [(i / (n - 1)) * def_["duration"] for i in range(n)]


def _decalage_pour(def_, radii, expr):
    epreuves = []
    for t in _dates(def_):
        pose = def_["pose"](t)
        contour = to_points(Silhouette(radii, rot=pose["sil"].rot, cx=pose["sil"].cx, cy=pose["sil"].cy, sx=pose["sil"].sx, sy=pose["sil"].sy), R)
        cal_contour = to_points(pose["sil"], R)
        v = _visage_de(def_, pose, expr)
        coins = []
        for dy in (-DERIVE_YAW, DERIVE_YAW):
            for dp in (-DERIVE_PITCH, DERIVE_PITCH):
                coins.append({
                    "gaze": {"yaw": v["gaze"]["yaw"] + dy, "pitch": v["gaze"]["pitch"] + dp, "roll": v["gaze"]["roll"]},
                    "split": v["split"],
                    "eyes": v["eyes"],
                })
        for c in coins:
            epreuves.append({
                "empreintes": _empreintes(c, pose["sil"], radii),
                "reference": _empreintes(c, pose["sil"], pose["sil"].radii),
                "contour": contour,
                "calContour": cal_contour,
            })
    return _resous(epreuves)


def build_table():
    """Build the full offset table keyed by shape id."""
    table = {}
    for forme in SHAPES:
        par = {}
        for def_ in STATES:
            if not def_["baseBody"]:
                continue
            exprs = ([None] + EXPRESSIONS) if def_["baseFace"] else [None]
            for expr in exprs:
                key = def_["id"] + "|" + (expr["id"] if expr else "")
                par[key] = _decalage_pour(def_, forme["radii"], expr)
        table[forme["id"]] = par
    return table
