#!/usr/bin/env python3
"""Regenerate src/bloub/_eyefit_table.py from the pose-space-deformation solver.

The runtime reads the committed table (_eyefit_table.py), which is keyed by
shape id and produced by tools/build_eyefit.py. This script re-runs the solver
(see bloub/eyefit.py) and writes the table; it should reproduce the committed
values bit for bit.

Usage:
    python tools/build_eyefit.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from bloub.eyefit import build_table  # noqa: E402


def _fmt(v):
    return repr(float(v))


def main():
    table = build_table()
    out = [
        '"""Eye offset table, generated by tools/build_eyefit.py.',
        "",
        "Keyed by shape id -> 'state|expression' -> (x, y) offset in ball-radius units.",
        "Do not edit by hand.",
        '"""',
        "",
        "TABLE = {",
    ]
    for shape_id in table:
        out.append("    " + repr(shape_id) + ": {")
        for key in table[shape_id]:
            x, y = table[shape_id][key]
            out.append("        " + repr(key) + ': {"x": ' + _fmt(x) + ', "y": ' + _fmt(y) + "},")
        out.append("    },")
    out.append("}")
    target = Path(__file__).resolve().parent.parent / "src" / "bloub" / "_eyefit_table.py"
    target.write_text("\n".join(out) + "\n", encoding="utf-8")
    print("wrote", target)


if __name__ == "__main__":
    main()
