#!/usr/bin/env python3
"""Regenerate src/bloub/profiles.py from the reference-video frames.

The bot's silhouettes are not drawn by hand: they are measured pixel by pixel
off the video, by sub-pixel ray casting from the shape's centroid. All bot
shapes are convex, so a radial profile r(theta) describes them exactly - and two
profiles sampled at the same angles morph by simple linear interpolation.

Prerequisites:
    pip install numpy pillow
    ffmpeg -i reference.mp4 -vf fps=10 frames/h_%04d.png

Usage:
    python tools/extract_profiles.py frames/ > src/bloub/profiles.py
"""

import math
import sys
from pathlib import Path

import numpy as np
from PIL import Image

BALL_R = 190.0
THRESHOLD = 128.0
SAMPLES = 64

# State -> reference image (frame index at 10 images/s) and note.
SHAPES = [
    ("egg", 164, "egg: same height as the ball, narrower in width"),
    ("hexagon", 174, "hexagon pointing up, very rounded corners"),
    ("triangle", 190, "triangle pointing up, very rounded corners"),
]


def load(path):
    a = np.asarray(Image.open(path).convert("RGB")).astype(float)
    luma = 0.299 * a[..., 0] + 0.587 * a[..., 1] + 0.114 * a[..., 2]
    return luma, a.max(2) - a.min(2)


def largest_blob(mask):
    h, w = mask.shape
    seen = np.zeros((h, w), bool)
    best = None
    ys, xs = np.nonzero(mask)
    for sy, sx in zip(ys, xs):
        if seen[sy, sx]:
            continue
        stack, pix = [(sy, sx)], []
        seen[sy, sx] = True
        while stack:
            y, x = stack.pop()
            pix.append((y, x))
            for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                ny, nx = y + dy, x + dx
                if 0 <= ny < h and 0 <= nx < w and mask[ny, nx] and not seen[ny, nx]:
                    seen[ny, nx] = True
                    stack.append((ny, nx))
        if best is None or len(pix) > len(best):
            best = pix
    return np.array(best)


def bilinear(img, x, y):
    h, w = img.shape
    x = np.clip(x, 0, w - 1.001)
    y = np.clip(y, 0, h - 1.001)
    x0, y0 = np.floor(x).astype(int), np.floor(y).astype(int)
    fx, fy = x - x0, y - y0
    return (img[y0, x0] * (1 - fx) * (1 - fy) + img[y0, x0 + 1] * fx * (1 - fy)
            + img[y0 + 1, x0] * (1 - fx) * fy + img[y0 + 1, x0 + 1] * fx * fy)


def profile(path):
    luma, sat = load(path)
    pix = largest_blob((luma < THRESHOLD) & (sat < 45))
    cy, cx = pix[:, 0].mean(), pix[:, 1].mean()

    angles = np.linspace(0, 2 * math.pi, SAMPLES, endpoint=False)
    steps = np.arange(0.5, 340.0, 0.25)
    radii = np.zeros(SAMPLES)
    for i, a in enumerate(angles):
        v = bilinear(luma, cx + math.cos(a) * steps, cy + math.sin(a) * steps)
        inside = v < THRESHOLD
        if not inside.any():
            continue
        k = int(np.nonzero(inside)[0].max())
        r = steps[k]
        if k + 1 < len(steps) and v[k + 1] != v[k]:
            r += 0.25 * (THRESHOLD - v[k]) / (v[k + 1] - v[k])
        radii[i] = r
    ys, xs = pix[:, 0], pix[:, 1]
    box = ((xs.max() - xs.min()) / BALL_R, (ys.max() - ys.min()) / BALL_R)
    return radii / BALL_R, box


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    frames = Path(sys.argv[1])
    out = [
        '"""Radial profiles r(theta) measured pixel-by-pixel from the reference video.',
        "",
        "theta = 0 points right and grows clockwise (y down).",
        "Unit: radius of the ball at rest = 1.",
        "",
        "Generated by tools/extract_profiles.py - do not edit by hand.",
        '"""',
        "",
        "PROFILE_SAMPLES = " + str(SAMPLES),
        "",
        "PROFILES = {",
    ]
    for name, frame, note in SHAPES:
        radii, (w, h) = profile(frames / ("h_%04d.png" % frame))
        out.append("    # " + note)
        out.append("    # image %d, footprint %.3f x %.3f" % (frame, w, h))
        out.append("    " + repr(name) + ": [" + ",".join("%.4f" % v for v in radii) + "],")
    out += ["}", ""]
    print("\n".join(out))


if __name__ == "__main__":
    main()
